
[package]
name = "engine"
version = "0.3.0"
authors = ["Dynisious <daniel.bechaz@gmail.com>"]
edition = "2018"

[dependencies]
vector = { version = "0.2.3", git = "http://github.com/Dynisious/engine" }
fixed-point = { versio = "0.1.2", git = "http://github.com/Dynisious/engine", optional = true }
