
[package]
name = "vector"
version = "0.2.3"
authors = ["Dynisious <daniel.bechaz@gmail.com>"]
edition = "2018"

[dependencies]
fixed-point = { version = "0.1.1", git = "https://github.com/Dynisious/engine", optional = true }
